src/SymboSim_Web_Application/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SymboSim_Web_Application.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/SymboSim_Web_Application/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SymboSim_Web_Application.Controllers
{
    public class LoginController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Register()
        {
            //ViewData["Message"] = "Your application description page.";

            return View();
        }
    }
}

src/SymboSim_Web_Application/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SymboSim_Web_Application.Controllers
{
    public class ProjectController : Controller
    {
        // GET: /<controller>/
        //public IActionResult Index()
        //{
        //    return View();
        //}
        public IActionResult Index(int id)
        {
            ViewData["ProjectNo"] = id;
            return View();
        }

        //[ChildActionOnly]
        //public ActionResult GetHtmlPage(string path)
        //{
        //    return new FilePathResult(path, "text/html");
        //}
    }
}

src/SymboSim_Web_Application/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/SymboSim_Web_Application/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/SymboSim_Web_Application/Views/Home/Index.cshtml
<link rel="stylesheet" href="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/styles/jqx.base.css" type="text/css" />

@*<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/scripts/demos.js"></script>*@
<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/jqxcore.js"></script>
<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/jqxsplitter.js"></script>
@*<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/jqxbuttons.js"></script>*@
@*<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/jqxscrollbar.js"></script>*@
<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/jqxpanel.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#mainSplitter').jqxSplitter({ width: '100%', height: '800px', panels: [{ size: '75%' }] });
    });
</script>


<div class="row">
    <div class="col-md-12">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div id='jqxWidget'>
                        <div id="mainSplitter" class="panel panel-default">
                            <div class="splitter-panel panel panel-info">
                                @*----------------------------------------------------- Panel 1 @*-----------------------------------------------------*@
                                <div class="panel-heading">Projects</div>
                                <div class="panel-body">
                                    <div class="panel panel-default project-item">
                                        <div class="panel-heading">Job #01</div>
                                        <div class="panel-body"><a href="#">This is the description of the first job</a></div>
                                    </div>
                                    <div class="panel panel-default project-item">
                                        <div class="panel-heading">Job #02</div>
                                        <div class="panel-body"><a href="#">This is the description of the second job</a></div>
                                    </div>
                                    <div class="panel panel-default project-item">
                                        <div class="panel-heading">Job #03</div>
                                        <div class="panel-body"><a href="#">This is the description of the second job</a></div>
                                    </div>
                                    <div class="panel panel-default project-item">
                                        <div class="panel-heading">Job #04</div>
                                        <div class="panel-body"><a href="#">This is the description of the second job</a></div>
                                    </div>
                                    <div class="panel panel-default project-item">
                                        <div class="panel-heading">Job #05</div>
                                        <div class="panel-body"><a href="#">This is the description of the second job</a></div>
                                    </div>
                                    <div class="panel panel-default project-item">
                                        <div class="panel-heading">Job #06</div>
                                        <div class="panel-body"><a href="#">This is the description of the second job</a></div>
                                    </div>
                                    <div class="panel panel-default project-item">
                                        <div class="panel-heading">Job #07</div>
                                        <div class="panel-body"><a href="#">This is the description of the second job</a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="splitter-panel panel panel-info">
                                @*----------------------------------------------------- Panel 2 @*-----------------------------------------------------*@
                                <div class="panel-heading">Job Status</div>
                                <div class="panel-body">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">Job #01</div>
                                        <div class="panel-body">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="progress">
                                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                                                            <a asp-area="" asp-controller="Project" asp-action="Index/1">Project 01 - 60%</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="progress">
                                                        <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 90%;">
                                                            <a asp-area="" asp-controller="Project" asp-action="Index/2">Project 02 - 90%</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/SymboSim_Web_Application/Views/Home/Index_original.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="http://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699562">Add an appsetting in config and access it in app.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

src/SymboSim_Web_Application/Views/Login/Index.cshtml
<div class="login-box">
    <div class="login-logo">
        <a href="../../index2.html"><b>SY</b>mbosim</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <form action="../../index2.html" method="post">
            <div class="form-group has-feedback">
                <input type="email" class="form-control" placeholder="Email">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" class="form-control" placeholder="Password">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox"> Remember Me
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                </div>
                <!-- /.col -->
            </div>
        </form>

        @*<a href="#">I forgot my password</a><br>*@
        <a asp-area="I forgot my password" asp-controller="Login" asp-action="Index">I forgot my password</a></br>
        @*<a href="register.html" class="text-center">Register a new membership</a>*@
        <a asp-area="Register" asp-controller="Login" asp-action="Register">Register</a>

    </div>
    <!-- /.login-box-body -->
</div>

src/SymboSim_Web_Application/Views/Login/Register.cshtml
<div class="register-box">
    <div class="register-logo">
        <a href="../../index2.html"><b>SY</b>mbosim</a>
    </div>

    <div class="register-box-body">
        <p class="login-box-msg">Register a new membership</p>

        <form action="../../index.html" method="post">
            <div class="form-group has-feedback">
                <input type="text" class="form-control" placeholder="First name">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="text" class="form-control" placeholder="Last name">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="email" class="form-control" placeholder="Email">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="text" class="form-control" placeholder="Affiliation">
                <span class="glyphicon glyphicon-briefcase form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="text" class="form-control" placeholder="Position">
                <span class="glyphicon glyphicon-cog form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" class="form-control" placeholder="Password">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" class="form-control" placeholder="Retype password">
                <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox"> I agree to the <a href="#">terms</a>
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                </div>
                <!-- /.col -->
            </div>
        </form>

        @*<a href="login.html" class="text-center">I already have a membership</a>*@
        <a asp-area="Register" asp-controller="Login" asp-action="Index">I already have a membership</a>
    </div>
    <!-- /.form-box -->
</div>

src/SymboSim_Web_Application/Views/Project/Index.cshtml
<link rel="stylesheet" href="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/styles/jqx.base.css" type="text/css" />
<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/scripts/demos.js"></script>
<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/jqxcore.js"></script>
<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/jqxbuttons.js"></script>
<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/jqxscrollbar.js"></script>
<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/jqxpanel.js"></script>
<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/jqxtree.js"></script>
<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/jqxexpander.js"></script>
<script type="text/javascript" src="http://www.jqwidgets.com/jquery-widgets-demo/jqwidgets/jqxsplitter.js"></script>


<script type="text/javascript">
    $(document).ready(function () {
        // Create jqxTree
        $('#jqxTree').jqxTree({ height: '100%', width: '100%' });
        $("#splitter1").jqxSplitter({ width: '100%', height: 600, panels: [{ size: 200 }] });
        $("#splitter2").jqxSplitter({ width: '100%', height: '100%', panels: [{ size: '25%' }] });
        $('#jqxTree').on('select', function (event) {
            //$("#ContentPanel").html("<div style='margin: 10px;'>" + event.args.element.id + "</div>");
            //$("#ContentPanel")("<div style='margin: 10px;'>" + event.args.element.id + "</div>");
        });
    });
</script>
<div class="panel panel-default">
    <div class="panel-heading">Project #@ViewData["ProjectNo"]</div>
    <div class="panel-body">
        <div id="splitter1">
            <div class="panel panel-default">
                <div class="panel-heading">Main Properties</div>
                <div class="panel-body" id='jqxTree'>
                    <ul>
                        <li id="Geometry" item-expanded='false'>
                            <span item-title="true">Geometry</span>
                            <ul>
                                <li id="Length" item-expanded='true'>
                                    <span item-title="true">Length</span>
                                </li>
                                <li id="Cross-Section" item-expanded='true'>
                                    <span item-title="true">Cross-Section</span>
                                </li>
                                <li id="X" item-expanded='true'>
                                    <span item-title="true">...</span>
                                </li>
                            </ul>
                        </li>
                        <li id="Material" item-expanded='false'>
                            <span item-title="true">Material</span>
                            <ul>
                                <li id="Prop1" item-expanded='true'>
                                    <span item-title="true">Prop1</span>
                                </li>
                                <li id="Prop2" item-expanded='true'>
                                    <span item-title="true">Prop2</span>
                                </li>
                                <li id="X" item-expanded='true'>
                                    <span item-title="true">...</span>
                                </li>
                            </ul>
                        </li>
                        <li id="Displacement" item-expanded='false'>
                            <span item-title="true">Displacement</span>
                            <ul>
                                <li id="Prop1" item-expanded='true'>
                                    <span item-title="true">Prop1</span>
                                </li>
                                <li id="Prop2" item-expanded='true'>
                                    <span item-title="true">Prop2</span>
                                </li>
                                <li id="X" item-expanded='true'>
                                    <span item-title="true">...</span>
                                </li>
                            </ul>
                        </li>
                        <li id="Rotations" item-expanded='false'>
                            <span item-title="true">Rotations</span>
                            <ul>
                                <li id="Prop1" item-expanded='true'>
                                    <span item-title="true">Prop1</span>
                                </li>
                                <li id="Prop2" item-expanded='true'>
                                    <span item-title="true">Prop2</span>
                                </li>
                                <li id="X" item-expanded='true'>
                                    <span item-title="true">...</span>
                                </li>
                            </ul>
                        </li>
                        <li id="Loads" item-expanded='false'>
                            <span item-title="true">Loads</span>
                            <ul>
                                <li id="Prop1" item-expanded='true'>
                                    <span item-title="true">Prop1</span>
                                </li>
                                <li id="Prop2" item-expanded='true'>
                                    <span item-title="true">Prop2</span>
                                </li>
                                <li id="X" item-expanded='true'>
                                    <span item-title="true">...</span>
                                </li>
                            </ul>
                        </li>
                        <li id="Simulation-Options" item-expanded='false'>
                            <span item-title="true">Simulation Options</span>
                            <ul>
                                <li id="Prop1" item-expanded='true'>
                                    <span item-title="true">Prop1</span>
                                </li>
                                <li id="Prop2" item-expanded='true'>
                                    <span item-title="true">Prop2</span>
                                </li>
                                <li id="X" item-expanded='true'>
                                    <span item-title="true">...</span>
                                </li>
                            </ul>
                        </li>
                        <li id="Job" item-expanded='false'>
                            <span item-title="true">Job</span>
                            <ul>
                                <li id="Prop1" item-expanded='true'>
                                    <span item-title="true">Prop1</span>
                                </li>
                                <li id="Prop2" item-expanded='true'>
                                    <span item-title="true">Prop2</span>
                                </li>
                                <li id="X" item-expanded='true'>
                                    <span item-title="true">...</span>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div id="ContentPanel">
                <div id="splitter2">
                    <div class="panel panel-default">
                        <div class="panel-heading">Sub Properties</div>
                        <div class="panel-body">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        </div>
                    </div>
                    <div class="panel panel-default">
                        @*<img src="~/images/Model-Image.png" alt="Model Viewer" width="100%" />*@
                        @*<img src="@Url.Content(string.Format("~/images/Model-Image{0}.jpg", ViewData["ProjectNo"]))" alt="Model Viewer" width="100%/>*@
                        @Html.Partial(Url.Content("BeamEditor"))
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/SymboSim_Web_Application/Views/Shared/BeamEditor.cshtml
<script src="~/lib/beam-viewer/lib/three.min.js"></script>
<script src="~/lib/beam-viewer/lib/OrbitControls.js"></script>
<script src="~/lib/beam-viewer/lib/dat.gui.min.js"></script>
<script src="~/lib/beam-viewer/lib/beams.js"></script>



@*<div style="position:absolute;left:10px;top:10px;">*@

<div>
    Set camera:<br />
    &nbsp;&nbsp;<label onclick="setCameraPosition('fit_view')">Fit view</label></br>
    &nbsp;&nbsp;<label onclick="setCameraPosition('xy_view')">X-Y view</label></br>
    &nbsp;&nbsp;<label onclick="setCameraPosition('yz_view')">Y-Z view</label></br>
    &nbsp;&nbsp;<label onclick="setCameraPosition('xz_view')">X-Z view</label></br>
    &nbsp;&nbsp;<label onclick="setCameraPosition()">Default view</label></br>
</div>
@*<div style="position:absolute;left:10px;top:20%;">*@
<div>
    <textarea id="point_cloud" rows="40" cols="20"></textarea>
    <br />
    <button onclick="drawPointCloud()">Plot point cloud</button>
</div>
<canvas id="display" style="width:100%; height:100%; position:absolute; top:0; right:0;"></canvas>

<script>
    init();
    animate();
</script>